2021-01-27 23:02:59,262 CRITICAL config_server_log.py Тестовое сообщение! Критическая ошибка
2021-01-27 23:02:59,262 ERROR config_server_log.py Тестовое сообщение! Ошибка
2021-01-27 23:02:59,262 DEBUG config_server_log.py Тестовое сообщение! Отладочная информация
2021-01-27 23:02:59,262 INFO config_server_log.py Тестовое сообщение! Информационное сообщение
2021-01-27 23:03:09,131 INFO server.py Запущен сервер, порт для подключений: 7777, 
2021-01-27 23:03:09,131 INFO server.py Адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-01-27 23:03:12,268 INFO server.py Установлено соедение с ПК ('127.0.0.1', 61135)
2021-01-27 23:03:12,268 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1611777792.2679417, 'user': {'account_name': 'Guest'}}
2021-01-27 23:03:12,268 DEBUG server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1611777792.2679417, 'user': {'account_name': 'Guest'}}
2021-01-27 23:03:12,268 INFO server.py Сформирован ответ клиенту {'response': 200}
2021-01-27 23:03:12,269 DEBUG server.py Соединение с клиентом ('127.0.0.1', 61135) закрывается.
